workflows:
  # iOS сборка для тестирования
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      node: 22
      cocoapods: default
    triggering:
      events: []
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      
      - name: Install Capacitor iOS
        script: |
          cd frontend
          npm install @capacitor/ios
      
      - name: Build web app
        script: |
          cd frontend
          npm run build
      
      - name: Add iOS platform and sync
        script: |
          cd frontend
          npx cap add ios || true
          npx cap sync ios
      
      - name: Install CocoaPods
        script: |
          cd frontend/ios/App
          pod install
      
      - name: Build iOS (Simulator)
        script: |
          cd frontend/ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath build \
            build
    
    artifacts:
      - frontend/ios/App/build/**/*.app

  # iOS Release для App Store
  ios-release:
    name: iOS Release (App Store)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      node: 22
      cocoapods: default
      groups:
        - ios_signing
    triggering:
      events: []
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      
      - name: Install Capacitor iOS
        script: |
          cd frontend
          npm install @capacitor/ios
      
      - name: Build web app
        script: |
          cd frontend
          npm run build
      
      - name: Add iOS platform and sync
        script: |
          cd frontend
          npx cap add ios || true
          npx cap sync ios
      
      - name: Install CocoaPods
        script: |
          cd frontend/ios/App
          pod install
      
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "uz.dehqonjon.app" --type IOS_APP_STORE
          keychain add-certificates
          xcode-project use-profiles
      
      - name: Build IPA
        script: |
          cd frontend/ios/App
          xcode-project build-ipa \
            --workspace App.xcworkspace \
            --scheme App
    
    artifacts:
      - frontend/ios/App/build/ios/ipa/*.ipa
