workflows:
  # Android сборка
  android-build:
    name: Android Build
    max_build_duration: 30
    instance_type: linux_x2
    environment:
      java: 17
      node: 18
      groups:
        - android_signing # Опционально: для подписи APK
    triggering:
      events: []  # Пустой = только manual trigger
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      
      - name: Build web app
        script: |
          cd frontend
          npm run build
      
      - name: Sync Capacitor
        script: |
          cd frontend
          npx cap sync android
      
      - name: Build Android APK
        script: |
          cd frontend/android
          ./gradlew assembleDebug
    
    artifacts:
      - frontend/android/app/build/outputs/**/*.apk
    
    publishing:
      email:
        recipients:
          - your-email@example.com  # Замени на свой email
        notify:
          success: true
          failure: true

  # Android Release (подписанный APK)
  android-release:
    name: Android Release
    max_build_duration: 30
    instance_type: linux_x2
    environment:
      java: 17
      node: 18
      groups:
        - android_signing
      vars:
        PACKAGE_NAME: "uz.dehqonjon.app"
    triggering:
      events: []
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      
      - name: Build web app
        script: |
          cd frontend
          npm run build
      
      - name: Sync Capacitor
        script: |
          cd frontend
          npx cap sync android
      
      - name: Build Android Release
        script: |
          cd frontend/android
          ./gradlew assembleRelease
    
    artifacts:
      - frontend/android/app/build/outputs/**/*.apk
      - frontend/android/app/build/outputs/**/mapping.txt

  # iOS сборка
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      node: 18
      cocoapods: default
    triggering:
      events: []
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      
      - name: Add iOS platform
        script: |
          cd frontend
          npm install @capacitor/ios
          npx cap add ios || true  # Игнорируем если уже добавлено
      
      - name: Build web app
        script: |
          cd frontend
          npm run build
      
      - name: Sync Capacitor iOS
        script: |
          cd frontend
          npx cap sync ios
      
      - name: Install CocoaPods
        script: |
          cd frontend/ios/App
          pod install
      
      - name: Build iOS (Simulator)
        script: |
          cd frontend/ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath build \
            build
    
    artifacts:
      - frontend/ios/App/build/**/*.app

  # iOS Release (для App Store)
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      node: 18
      cocoapods: default
      groups:
        - ios_signing  # Нужны сертификаты Apple
    triggering:
      events: []
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install
      
      - name: Add iOS platform
        script: |
          cd frontend
          npm install @capacitor/ios
          npx cap add ios || true
      
      - name: Build web app
        script: |
          cd frontend
          npm run build
      
      - name: Sync Capacitor iOS
        script: |
          cd frontend
          npx cap sync ios
      
      - name: Install CocoaPods
        script: |
          cd frontend/ios/App
          pod install
      
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "uz.dehqonjon.app" --type IOS_APP_STORE
          keychain add-certificates
          xcode-project use-profiles
      
      - name: Build IPA
        script: |
          cd frontend/ios/App
          xcode-project build-ipa \
            --workspace App.xcworkspace \
            --scheme App
    
    artifacts:
      - frontend/ios/App/build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
