workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      node: 22
      cocoapods: default
    triggering:
      events: []
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install
          npm install @capacitor/ios
      
      - name: Build web app
        script: |
          cd frontend
          npm run build
      
      - name: Setup iOS and build
        script: |
          cd frontend
          
          # Add iOS platform
          npx cap add ios || echo "iOS platform may already exist"
          
          # Sync
          npx cap sync ios
          
          # Check if ios folder exists
          ls -la ios/
          
          # Install pods
          cd ios/App
          pod install
          
          # Build
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -destination 'generic/platform=iOS Simulator' \
            -derivedDataPath build \
            build
    
    artifacts:
      - frontend/ios/App/build/**/*.app

  ios-release:
    name: iOS Release (App Store)
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      xcode: latest
      node: 22
      cocoapods: default
      groups:
        - ios_signing
    triggering:
      events: []
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          npm install
          npm install @capacitor/ios
      
      - name: Build web app
        script: |
          cd frontend
          npm run build
      
      - name: Setup iOS
        script: |
          cd frontend
          npx cap add ios || echo "iOS platform may already exist"
          npx cap sync ios
          cd ios/App
          pod install
      
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "uz.dehqonjon.app" --type IOS_APP_STORE
          keychain add-certificates
          xcode-project use-profiles
      
      - name: Build IPA
        script: |
          cd frontend/ios/App
          xcode-project build-ipa \
            --workspace App.xcworkspace \
            --scheme App
    
    artifacts:
      - frontend/ios/App/build/ios/ipa/*.ipa
